/**
 * Correspondance nom de banque → identité visuelle + logo officiel.
 * Sources logos : Wikimedia Commons (licences libres).
 */
const BANK_CONFIGS = [
  {
    key: 'poste',
    match: /algérie\s*poste|algerie\s*poste|alger\s*poste|\bccp\b|bureau de poste|la poste|\bposte\b|distributeur.*poste|gab.*poste|\bptt\b/i,
    abbr: 'AP',
    bg: '#F7A600',
    text: '#fff',
    label: 'Algérie Poste',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/72/AlgeriePoste.svg',
  },
  {
    key: 'bna',
    match: /\bBNA\b|B\.N\.A\.?|banque nationale d.algérie|banque nationale d.algerie|البنك الوطني الجزائري/i,
    abbr: 'BNA',
    bg: '#006633',
    text: '#fff',
    label: 'BNA',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Bna-logo.svg',
  },
  {
    key: 'bea',
    match: /\bBEA\b|B\.E\.A\.?|banque ext[eé]rieure|algeria.s external bank|بنك الجزائر الخارجي/i,
    abbr: 'BEA',
    bg: '#003F87',
    text: '#fff',
    label: 'BEA',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/e/e9/BEA.svg',
  },
  {
    key: 'cpa',
    match: /\bCPA\b|cr[eé]dit populaire|algerian popular loan|القرض الشعبي الجزائري/i,
    abbr: 'CPA',
    bg: '#C8102E',
    text: '#fff',
    label: 'CPA',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/d/dd/Cr%C3%A9dit_populaire_d%27Alg%C3%A9rie_logo.svg',
  },
  {
    key: 'badr',
    match: /\bBADR\b|B\.A\.D\.R\.?|banque.*(agriculture|d[eé]veloppement rural)|agricultural development bank|التنمية الفلاحية|بنك الفلاحة/i,
    abbr: 'BADR',
    bg: '#1E7D3B',
    text: '#fff',
    label: 'BADR',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/5/5c/Banque_de_l%E2%80%99agriculture_et_du_d%C3%A9veloppement_rural.svg',
  },
  {
    key: 'bdl',
    match: /\bBDL\b|B\.D\.L\.?|banque de d[eé]veloppement local|بنك التنمية المحلية/i,
    abbr: 'BDL',
    bg: '#1565C0',
    text: '#fff',
    label: 'BDL',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Logo_BDL_Banque_DZ.svg',
  },
  {
    key: 'cnep',
    match: /\bCNEP\b|cnep.bank|caisse nationale d.[eé]pargne|الصندوق الوطني للتوفير/i,
    abbr: 'CNEP',
    bg: '#0D47A1',
    text: '#fff',
    label: 'CNEP',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Logo_CNEP_banque_DZ.svg',
  },
  {
    key: 'agb',
    match: /\bAGB\b|A\.G\.B\.?|algeria gulf bank|algerian gulf bank|arab gulf bank|gulf bank alger|بنك الخليج الجزائر/i,
    abbr: 'AGB',
    bg: '#1B2F6B',
    text: '#F7C52D',
    label: 'AGB',
    logoUrl: '/logos/agb_bank_logo.png',
  },
  {
    key: 'albaraka',
    match: /al.?baraka/i,
    abbr: 'AB',
    bg: '#006B3F',
    text: '#fff',
    label: 'Al Baraka',
    logoUrl: '/logos/AL_Braka_bank_logo.png',
  },
  {
    key: 'alsalam',
    match: /al.?salam\s*bank|banque\s*es.?salam|\bes.?salam\b|مصرف السلام|بنك السلام/i,
    abbr: 'ES',
    bg: '#1B5E20',
    text: '#FFD700',
    label: 'Banque Es Salam',
    logoUrl: '/logos/Essalam_bank_logo.png',
  },
  {
    key: 'bnp',
    match: /bnp\s*paribas/i,
    abbr: 'BNP',
    bg: '#00965E',
    text: '#fff',
    label: 'BNP Paribas',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/85/BNP_Paribas_logo.svg',
  },
  {
    key: 'sga',
    match: /société générale|societe generale|\bSGA\b/i,
    abbr: 'SGA',
    bg: '#E30613',
    text: '#fff',
    label: 'SGA',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Logo-SG-Soci%C3%A9t%C3%A9-G%C3%A9n%C3%A9rale.svg',
    logoSize: 34,
  },
  {
    key: 'natixis',
    match: /natixis/i,
    abbr: 'NAT',
    bg: '#7B1FA2',
    text: '#fff',
    label: 'Natixis',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Natixis.svg',
  },
  {
    key: 'abc',
    match: /\bABC\b|arab banking corporation/i,
    abbr: 'ABC',
    bg: '#003F7F',
    text: '#fff',
    label: 'Bank ABC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/BankABCLogo.svg',
    logoSize: 30,
  },
  {
    key: 'arab',
    match: /\barab bank\b|البنك العربي/i,
    abbr: 'ARB',
    bg: '#0D47A1',
    text: '#fff',
    label: 'Arab Bank',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Arab_Bank.svg',
  },
  {
    key: 'housing',
    match: /housing bank|\bHBTF\b/i,
    abbr: 'HB',
    bg: '#0277BD',
    text: '#fff',
    label: 'Housing Bank',
    logoUrl: '/logos/housing_bank_logo.png',
  },
  {
    key: 'fransabank',
    match: /fransabank/i,
    abbr: 'FB',
    bg: '#1A237E',
    text: '#fff',
    label: 'Fransabank',
    logoUrl: 'https://www.fransabank.dz/wp-content/themes/finbank-child/images/logo-fr.png',
  },
  {
    key: 'trust',
    match: /trust\s*bank/i,
    abbr: 'TB',
    bg: '#37474F',
    text: '#fff',
    label: 'Trust Bank',
    logoUrl: 'https://www.trustbank.dz/templates/trust/img/logo.png',
  },
  {
    key: 'citi',
    match: /citibank/i,
    abbr: 'CITI',
    bg: '#003B70',
    text: '#fff',
    label: 'Citibank',
    logoUrl: null,
  },
  {
    key: 'arba',
    match: /arba\s*bank|بنك الأربعاء/i,
    abbr: 'ARB',
    bg: '#1A5276',
    text: '#fff',
    label: 'Arba Bank',
    logoUrl: null,
  },
  // ── Banques françaises ──────────────────────────────────────────────────────
  {
    key: 'credit-agricole',
    match: /crédit\s*agricole|credit\s*agricole|caisse\s+(r[eé]gionale|locale)/i,
    abbr: 'CA',
    bg: '#008A00',
    text: '#fff',
    label: 'Crédit Agricole',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Logo_Cr%C3%A9dit_Agricole.svg',
  },
  {
    key: 'lcl',
    match: /\blcl\b|lyonnais/i,
    abbr: 'LCL',
    bg: '#D20019',
    text: '#fff',
    label: 'LCL',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/LCL_banque_logo.svg',
  },
  {
    key: 'banque-postale',
    match: /banque\s*postale|la\s*poste(?!\s*(alg[eé]r|dz))/i,
    abbr: 'LP',
    bg: '#F7A600',
    text: '#fff',
    label: 'La Banque Postale',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_La_Banque_postale_2022.svg',
  },
  {
    key: 'cic',
    match: /\bcic\b|cr[eé]dit\s*industriel/i,
    abbr: 'CIC',
    bg: '#003B8E',
    text: '#fff',
    label: 'CIC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/CIC_logo_2021.svg',
  },
  {
    key: 'credit-mutuel',
    match: /cr[eé]dit\s*mutuel/i,
    abbr: 'CM',
    bg: '#003189',
    text: '#fff',
    label: 'Crédit Mutuel',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/28/Cr%C3%A9dit_Mutuel_2022_logo.svg',
  },
  {
    key: 'bred',
    match: /\bbred\b/i,
    abbr: 'BRED',
    bg: '#0055A5',
    text: '#fff',
    label: 'Bred',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Banque_Populaire_2018_logo.svg',
  },
  {
    key: 'banque-populaire',
    match: /banque\s*populaire/i,
    abbr: 'BP',
    bg: '#0066CC',
    text: '#fff',
    label: 'Banque Populaire',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Banque_Populaire_2018_logo.svg',
  },
  {
    key: 'caisse-epargne',
    match: /caisse\s+d.?[eé]pargne/i,
    abbr: 'CE',
    bg: '#8B1A1A',
    text: '#fff',
    label: "Caisse d'Épargne",
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Caisse_d%27%C3%A9pargne_logo.svg',
  },
  {
    key: 'hsbc',
    match: /\bhsbc\b/i,
    abbr: 'HSBC',
    bg: '#DB0011',
    text: '#fff',
    label: 'HSBC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/HSBC_logo_%282018%29.svg',
  },
];

/**
 * Retourne la config visuelle d'une banque selon le nom du DAB.
 * @param {string} nom
 * @returns {{ abbr, bg, text, label, key, logoUrl } | null}
 */
export const getBankConfig = (nom) => {
  if (!nom) return null;
  return BANK_CONFIGS.find((b) => b.match.test(nom)) || null;
};
